services:
  db:
    image: timescale/timescaledb:2.18.1-pg16
    container_name: algotrader_db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-algotrader}
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME:-algotrader},${TEST_DB_NAME:-algotrader_test}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-algotrader}"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - algotrader_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  algotrader_network:
    driver: bridge
